### ISSUE TITLE
Support NodeJS 18 or higher since 16 is deprecated

### ISSUE THREAD

**Issue by ghiscoding** [step-security/wait-for-secrets#183]
Hello, thanks for this GitHub Action package, I use it in a few of my open source projects, however I'm getting a warning from GitHub Action that Node16 are deprecated and eventually migrated (or fail). Below is the warning I'm currently receiving after an NPM release using this action

```sh
[deploy-npm-latest](https://github.com/lerna-lite/lerna-lite/actions/runs/8530155212/job/23367421675)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: step-security/wait-for-secrets@v1. 

For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
```

**Comment by varunsh-coder** [comment]
@ghiscoding apologies for the delay in responding. Thanks for using this action! The issue has been resolved now. v1.2.0 (v1 has been updated to point to it) uses node20 so you should not see the warning now.

**Comment by ghiscoding** [comment]
awesome thanks a lot, and no worries for the delay 😃 you can probably close the issue if you think it's completed, I won't have a chance to test it until a few more days. Again thanks a lot 👍🏻

**Comment by varunsh-coder** [comment]
ok, I did test it. So closing it. Feel free to re-open if you see any issue.
